name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        default: '1.0.0-preview-arm-image'

env:
  Version: ${{ github.event.inputs.releaseVersion }}
  
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker buildx build --platform=linux/arm64 --push --file Dockerfile --tag sarvesh2021/baget-v2:${{ github.event.inputs.releaseVersion }} --tag sarvesh2021/baget-v2:latest .
